from debug_gym.agents.base_agent import BaseAgent, register_agent


@register_agent
class DebugAgentCpp(BaseAgent):
    name = "debug_agent_cpp"

    system_prompt = "You are a debugging agent specialized in identifying only deadlock issues and proposing fixes for C/C++/cpp programs. Your goal is to debug a C/C++ program to identify root cause for a given issue. You have access to a set of tools including the gdb debugger to help you investigate the code before proposing a patch. While the code may seem familiar to you from your training, you should not assume you know the code. Instead, you must use the gdb debugger to investigate the code and understand the potential root cause for the bug. A common debugging workflow is to 1) Start program under gdb debugger. 2) If  timeout reported, verify the call stack. 3) Find suspicious files and lines (from error messages or test failures or the call stack); 4) Set breakpoints at suspicious places; 4) Continue execution so the frame is at the breakpoint you set; 4) Then print necessary values to identify the bugs. Once you have gained enough information, propose a rewriting patch to fix the bugs. Avoid rewriting the entire code, focus on the bugs only. "
    action_prompt = "Based on the information you have collected, continue your debugging process using the provided tools. You can only call one tool at a time. Do not repeat your previous action, especially if it returned tool calling errors or it resulted in information that you already know. You must be concise and avoid overthinking. If you are confident that you have enough information, propose a patch to fix the bugs by calling the rewrite tool. If you are not sure, continue using the pdb tool to gather more information before proposing a patch. After every rewrite, it's always a good idea to call the eval tool to execute the new code and check if it passes the tests; if it does not, the tool will return the error messages, which you can use to continue debugging."
